//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LianaSkryleva320_AnimalsPhoto.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public string Age { get; set; }
        public Nullable<System.TimeSpan> WhenWakeUp { get; set; }
        public Nullable<System.TimeSpan> WhenEat { get; set; }
        public string HowLifeInNowDay { get; set; }
        public Nullable<int> IDType { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
